### ISSUE TITLE
Translator failed due to not finding jparacrawl

### ISSUE THREAD

**Issue by s3779792** [zyddnys/manga-image-translator#132]
![image](https://user-images.githubusercontent.com/50536249/205436038-7bcd0acc-797c-4fb8-9e1a-05e27073383b.png)

**Comment by thatDudo** [comment]
Seems like the sugoi model has not been downloaded yet. It seems there was a check for whether the ./models/translators/jparacrawl directory exists and it returned false. This shouldnt happen since if the folder really didnt existed it should have detected that at an earlier stage and redownloaded the models... Not really sure what is causing this weird behaviour. can you manually check if the folder exists or not?

**Comment by s3779792** [comment]
Manual check didn't show the folder, don't know what I did, but it works now... weird.
