### ISSUE TITLE
Getting Error when running the script on Git Bash (plus other similar console)

### ISSUE THREAD

**Issue by Noxsser** [zyddnys/manga-image-translator#182]
I keep getting this error when its close to completing the translation.

![image](https://user-images.githubusercontent.com/67326196/211566115-2990e4ea-32b3-40e6-b007-ba62e65592c4.png)

Im using Python 3.10.9. It did get install from Microsoft store when I run the command to install it.

would this be caused by the version of python that I am using?

**Comment by My12123** [comment]
To run on Windows you need to install anaconda (https://ww.anaconda.com/) or Miniconda (because of PyTorch) and install PyTorch suitable (CPU or GPU) (https:/pych.org/-started////locally) 
Git Bash will not be able to install PyTorch.
![2023-01-10_17-12-49](https://user-images.githubusercontent.com/49092250/211574108-b242a486-c380-4d52-a6ef-d6cb51c743c7.png)
![2023-01-10_17-14-43](https://user-images.githubusercontent.com/49092250/211575132-e31bc71a-4763-41d0-bb4f-d3e0724bc92e.png)
![2023-01-10_17-16-38](https://user-images.githubusercontent.com/49092250/211575262-f21168dc-4ace-4a8a-9609-11944e74714d.png)
![2023-01-10_17-03-05](https://user-images.githubusercontent.com/49092250/211573780-cfef4b3b-b782-4d26-9b93-d62d8c0be1de.png)
First install Pwtorch for the appropriate CPU version of the commands conda install pytorch torchvision torchaudio cpuonly -c pytorch или GPU conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
Then continue installing pip install -r requirements.txt
![2023-01-10_17-29-43](https://user-images.githubusercontent.com/49092250/211578193-33b296ea-d34b-4cc1-8657-e44da4e55755.png)

**Comment by thatDudo** [comment]
Not quite sure why you get this error. Maybe try running this on windows cmd instead of git bash, otherwise remove `--verbose` flag to remove the debug prints.

**Comment by Noxsser** [comment]
Thank you!! I found another way to fix it, it was apparently caused by the different versions of python that I had on my system (leftovers from months ago) and once I did a full clean install it worked.

I should have used anaconda from the start since it looks way better at handling this. Again thank you!!
