### ISSUE TITLE
Is there an exe version for Web Mode?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#183]
I also want the code that you can collect exe file yourself. In the Anaconda environment.

**Comment by singersbalm** [comment]
It seems like there isn’t. The release tab doesn’t contain an exe. Why would you want an exe anyway? Just run it in a docker container. If you don’t want to do that you could just compile it yourself: https://www.dice.com/career-advice/4-fast-python-compilers-better-performance

i don’t use windows, but my guess is that it would actually perform better and be more stable in docker just because it’s linux, but that’s just a guess

**Comment by My12123** [comment]
exe is needed for fast snack apps and a bowl of everything without a console. This (https://www.dice.com/career-advice/4-fast-python-compilers-better-performance) site is not exactly what I need this comparison, and I need to build in exe.

**Comment by singersbalm** [comment]
I don’t really get what you are trying to tell me. I’ couldn’t find anything on fast snack apps when I googled it. If you want to reduce the terminal output don’t use verbose. If you want to run a Webapp as an executable you could use cefpython or flexx

**Comment by My12123** [comment]
I found how to build in exe file  https://habr-com.translate.goog/ru/company/vdsina/blog/557316/?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp
