### ISSUE TITLE
ERROR: [demo] Exception: No input image was supplied. Use -i <image_path>

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#212]
(Mt) F:\manga-image-translator-main>F:\manga-image-translator-main\run.bat
fatal: not a git repository (or any of the parent directories): .git
[demo] Running in demo mode
ERROR: [demo] Exception: No input image was supplied. Use -i <image_path>

I don’t use git.

**Comment by thatDudo** [comment]
Im afraid pip wont make things much better for you then since it wouldnt reflect the current release branch but merely a version that might be months old (depending on how often we update). You would also have to run it manually as I said.

That automatic updater that runs on start up you are referring to would have to redownload the whole repository on every little change, which is very inefficient compared to git.

If youve taken the time to install python you might as well just do the same with git.

**Comment by My12123** [comment]
![2023-02-16_20-27-46](https://user-images.githubusercontent.com/49092250/219442036-847ef0f0-ccf2-42d0-87e6-4254f1f26bd1.png)

**Comment by thatDudo** [comment]
You have to rerun pip install requirements.txt

**Comment by My12123** [comment]
Can I make a code (run.bat) that just updates without running?

**Comment by thatDudo** [comment]
Run `git pull` for that.

**Comment by My12123** [comment]
fatal: not a git repository (or any of the parent directories): .git
![2023-02-16_20-41-25](https://user-images.githubusercontent.com/49092250/219445415-2049d4b2-6f2b-4982-9a5c-10eaf7a81f14.png)

**Comment by thatDudo** [comment]
That is because you ran it from a different directory. Can you try it again? I added a commit and I cant test bcs Im on linux.

**Comment by My12123** [comment]
![2023-02-16_21-34-21](https://user-images.githubusercontent.com/49092250/219456577-7fccf0f0-f650-42f7-a435-ae78c32f07e0.png)

**Comment by My12123** [comment]
@thatDudo 
![2023-02-23_11-35-29](https://user-images.githubusercontent.com/49092250/220857802-96a4e83b-3789-4737-b39c-53d5755254f2.png)
![2023-02-23_11-36-37](https://user-images.githubusercontent.com/49092250/220857820-f9c1c936-cdf4-4ec2-bd85-d856df21a3cd.png)
[update.zip](https://github.com/zyddnys/manga-image-translator/files/10811639/update.zip)
