### ISSUE TITLE
Can I use wider area while text rendering process?

### ISSUE THREAD

**Issue by ppkppk8520** [zyddnys/manga-image-translator#22]
Because it is awkward that reading text vertically, I modified text_render.py to always render text horizontally.
But since original text area is too narrow, this result is still hard to read.
So, I want to know it is possible to modify code to use more wider area while text rendering process.(and how to)

Sorry for my poor English and thanks in advance.

**Comment by zyddnys** [comment]
The only information available to the text renderer is the original text line positions, so if the original text is vertical and translated text is horizontal the rendered text will be too narrow.
You need a way to figure out where to put translated horizontal texts, which I can't figure out how to do.
As stated in  `README.md`:
```
5. Text rendering area is determined by detected text lines, not speech bubbles. This works for images without speech bubbles, but making it impossible to decide where to put translated English text. I have no idea how to solve this.
```

**Comment by ppkppk8520** [comment]
thanks for notifying me!

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/167295402-9795186c-8c32-4642-bac3-9a07186d6364.png)
``5. Text rendering area is determined by detected text lines, not speech bubbles. This works for images without speech bubbles, but making it impossible to decide where to put translated English text. I have no idea how to solve this.``
Doesn't this basically contain the solution on how to fix it(at least for images with speech bubbles): Detect the area of the speech bubble(if there is one), and then put the text in there in a somewhat fitting horizontal way.
![grafik](https://user-images.githubusercontent.com/5133936/167295652-ce77482a-3c70-4824-91e0-84cf85de70c7.png)

For images without any bubbles a first fix could be to give an option to flip the characters 90° to the left or right, so you can read it as a flowing text, instead of characters stacked ontop of each other.

**Comment by marcussacana** [comment]
I has wrote a modification in the past year to this tool, that used the inpainting image to search the limit of the solid background color in the bubble and with that I was able to expand the text render area in a better way, well, I never pushed because I did in C# and called from python, isn't good for the project the way that I did it.

**Comment by marcussacana** [comment]
Here, I did with this code: https://gist.github.com/marcussacana/2e6bfa87ebb1a6b11eb41708125aba7d
And I called like this
```py
	import clr
	clr.AddReference("TextDraw")
	from TextDraw import GDI
	GDI.DrawText('./result/render.png', trans_text,  region.x, region.y, region.w, region.h, (255 << 24)|(region.fg_r << 16)|(region.fg_g << 8)|region.fg_b)
```

**Comment by Snowad14** [comment]
> Here, I did with this code: https://gist.github.com/marcussacana/2e6bfa87ebb1a6b11eb41708125aba7d And I called like this
> 
> ```python
> 	import clr
> 	clr.AddReference("TextDraw")
> 	from TextDraw import GDI
> 	GDI.DrawText('./result/render.png', trans_text,  region.x, region.y, region.w, region.h, (255 << 24)|(region.fg_r << 16)|(region.fg_g << 8)|region.fg_b)
> ```
> 
> the output has like this: ![image](https://user-images.githubusercontent.com/10576957/167314642-3e153e8c-bb9b-4cb4-a734-475b3c957c74.png)

I had a little trouble rewriting it on the new version but it gave me more readable results even if I think it's mostly the way the text is rendered that changes. 

![Normal](https://user-images.githubusercontent.com/67842535/174318793-23e87eba-a1b2-4d72-8b2e-ae0ec760d94b.jpg)
![MangaENG](https://user-images.githubusercontent.com/67842535/174318817-bf284067-048a-40eb-b6f2-777864d59d65.jpg)
![New](https://user-images.githubusercontent.com/67842535/174318832-ba1f4703-230c-48e0-8bac-05571af68625.png)

**Comment by marcussacana** [comment]
Ohh, maybe this: 
![image](https://user-images.githubusercontent.com/10576957/174325106-5dd3a6f6-ba6e-4b52-9687-93b1d076dbd5.png)
very hard to see, but the image isn't really clean, this small detail stopped the text region to be expanded.

**Comment by Snowad14** [comment]
![25](https://user-images.githubusercontent.com/67842535/174334770-262aef75-e296-40ba-a88f-c3893e5a04b2.jpg)
I don't think so, I tried with other ones that come from manga PLUS and it was always a bit the same

**Comment by marcussacana** [comment]
Only debugging then, maybe a bug, because I remember well that thing as one of the worst part writing that code.

**Comment by marcussacana** [comment]
Ohh, during the call you set the argument `NoExpand` to true maybe?
