### ISSUE TITLE
May I know which dataset you used to train the model? (ocr, inpainting,detect)

### ISSUE THREAD

**Issue by qwopqwop200** [zyddnys/manga-image-translator#25]

**Comment by zyddnys** [comment]
detection and OCR are trained using a custom synth data (you can find the text rendering code in https://github.com/zyddnys/manga-image-translator/tree/main/text_rendering), inpainting is trained on danbooru2020 rendered text as mask.

**Comment by qwopqwop200** [comment]
thank you.

**Comment by qwopqwop200** [comment]
I have three additional questions.
First, did both text detection and OCR learn from synthetic data based on danbooru2020?
Second, did you train using all the datasets in danbooru 2020 (4.22m images with a data size of 3.4TB)?
Third,How many fonts did you use to train? Can you give me a list of fonts if you don't mind?

**Comment by zyddnys** [comment]
I use a combination of danbooru2020, coco and imagenet, and manga109 dataset as background to train text detection and OCR.
I use danbooru2020 (3.4TB version) to train inpainting, code can be found here https://github.com/zyddnys/anime-inpainting-deq
I use about 3000 font files I collected, I don't have a list since many of them are actually unusable.

**Comment by leminhyen2** [comment]
I find it mind boggling that you seemed to write a custom model for everything. For OCR, are you reimplementing any specific paper or it's a combination of a few to fit your needs? 

Thanks for open-sourcing this repo btw, I find it very interesting

**Comment by zyddnys** [comment]
For OCR I have to use my own model because no other OCR tools support extracting text font color and border color. The OCR model is just a ConvNet followed a transformer encoder-decoder model.

**Comment by leminhyen2** [comment]
If I get it right, the model is similar to the one in "An Image is Worth 16x16 Words" paper but with ConvNet. 

Border color I understand as many text rendered in background with outline. But I thought text color are always taken into account when training?

**Comment by zyddnys** [comment]
I didn't use VIT (yet), the ConvNet turns text line image with height 48 width any channels 3 to a strip of feature which is then fed into a seq2seq model (transformer encoder-decoder) to decode text, font color and border color.
I need both font and border color so later I can draw translated texts in correct color. Not all images/manga are black and white, many images and videos use text color to identify characters, not bubbles.

**Comment by leminhyen2** [comment]
Ah, thanks for the info. Just one more question, do you use GPU for your website demo and basically what's the spec of your server. I'm surprised that for a heavy deep learning stack like this, it ran quite fast

**Comment by zyddnys** [comment]
I use a GCP server without any GPU, just a 4 core 16G RAM AMD EPYC config. It used to have a Tesla T4 which runs even faster (you can get result in 2 seconds), but I it was expensive and serves no purpose as a demo so I now just use CPU.

**Comment by qwopqwop200** [comment]
It doesn't matter if it doesn't work, can you give me a list of the names of the 3000 fonts you've collected? I'm training OCR model separately, but I'm having a lot of difficulty in the font part.
\

**Comment by mspykerez** [comment]
@zyddnys 

Great work with the all OCR detection/replacement, we have been discussing it on discord.
Only issue that I see is with the translation text being shown on a weird vertical way instead of horizontal when the target language is english.

Btw if you interested in joining the bandwagon for the translation model being trained that works offline https://www.reddit.com/r/visualnovels/comments/qnsgd2/from_sugoi_translator_developer_today_i_will_send/
the discord is https://discord.gg/XFbWSjMHJh

**Comment by zyddnys** [comment]
English is rendered vertically because the original text is vertical, since I only detect text lines not bubbles if I use the detected region to draw English text it will all be squeezed together. The problem is that many images contains not bubbles and only comes with places to put vertical texts, if I forcefully put horizontal texts they will cover important parts of the image. I currently don't have a solution to address this problem since it requires understanding the underlying image content as well as the text. However I can add an option to force text rendered horizontally later.

**Comment by zyddnys** [comment]
> It doesn't matter if it doesn't work.Can you give me a list of 3000 font names? i am training the OCR model separately, but the font part is very difficult.

Here https://github.com/zyddnys/manga-image-translator/blob/main/training/all-fonts.txt

**Comment by qwopqwop200** [comment]
Thank you very much.

**Comment by qwopqwop200** [comment]
I'm sorry, some fonts are not searched by name.I think the font name list is not enough.I'm sorry to bother you, but can you share the compressed font file?
