### ISSUE TITLE
I'm a dummy at tech, and don't know how to set it up

### ISSUE THREAD

**Issue by ElbyM4** [zyddnys/manga-image-translator#37]
I'm not extremly tech savvy, so I don't know how to set it up, could you please maybe post a more descriptive description of how to do it?

**Comment by ElbyM4** [comment]
I don't get most of the big boy words, something like "Yeah just throw it into the "user" folder" would be of great help!

**Comment by ElbyM4** [comment]
Also, love the web demo, it works great!

**Comment by Eidenz** [comment]
The current "How to use" in the readme file should be pretty explicit though. Maybe missing a step "install requirements with `pip install requirements.txt`".

What are you having difficulties with?

**Comment by ElbyM4** [comment]
So I just have to download ocr.ckpt、detect.ckpt, comictextdetector.pt and inpainting.ckpt, all the softwares and code stated in "requirements.txt" and then just put them all into the manga-image-translator-main?

**Comment by Eidenz** [comment]
Yeah, you basically put all these files in the folder, run the install command and you should be set up to use it.

I also made an alternate version of the demo, more optimized for English translation as it runs with DeepL as mentioned in #38.
I aim to keep the service running 24/7 for free since it's not using too much of my resources.

**Comment by ElbyM4** [comment]
Thanks, very helpful!
