### ISSUE TITLE
Is lama impainter implemented?

### ISSUE THREAD

**Issue by Curlypla** [zyddnys/manga-image-translator#60]
I changed the default on lama and downloaded his model but I got errors so I was wondering if it was implemented?

**Comment by mspykerez** [comment]
I'd like to know if that is the case for the latest release too since the changelog doesn't mention it.
Also on the changelog where it says ''Added English text renderer by dmMaze'' @zyddnys  seems to have mistyped the wrong Github page of @dmMaze 

On another note, the official online demo is not rendering the english translated text horizontal even when we select the horizontal option there.

**Comment by Snowad14** [comment]
The version of dmMaze is perfectly functional but you must use the terminal version with the argument --manga2eng

**Comment by zyddnys** [comment]
lama is still being trained
